spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/SEMIP-FOLIOS
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
