spring:
  jpa:
    database: oracle
  datasource:
    url: jdbc:oracle:thin:@192.168.2.1:1900:xe
    username: CONSFARMACIA
    password: 12345678
    driver-class-name: oracle.jdbc.driver.OracleDriver